### ISSUE TITLE
Asia/Kolkata is not supported in the timezone map, but Asia/Calcutta which is the older name is supported

### ISSUE THREAD

**Issue by mansapabbaraju** [mitsuhiko/localzone#3]
Thank you, this is very helpful. One issue I found while using this: Asia/Kolkata is not supported in the timezone map, but Asia/Calcutta which is the older name is supported.
Same with UTC 

Probably need to update the data from CLDR repository?

**Comment by mitsuhiko** [comment]
I assume you are referring to the windows mapping?  The zone info there comes from CLDR which stores `Asia/Calcutta`: https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml

Can you clarify what issue you are running into exactly?

**Comment by mansapabbaraju** [comment]
Yes, I am referring to the windows mapping. The issue I see is:

When I try to convert IANA timezone `Asia/Kolkata` to its corresponding windows timezone. You are right, this timezone is not included in the CLDR database, I saw several other complaints with this issue:
For example:
https://stackoverflow.com/questions/17348807/how-to-translate-between-windows-and-iana-time-zones

However, `Asia/Kolkata` is indeed a valid IANA timezone. To overcome this, I am creating a new map with these additional mappings in addition to using the map in this crate. Just wanted to bring this to your notice. 

`Calcutta` is the older name of the city, and `Kolkata` happens to be the new name. However, it seems like CLDR has not updated its database for several years relating to this mapping

**Comment by mitsuhiko** [comment]
That's to be expected.  You cannot assume that the mapping from IANA to windows time zone succeeds as the latter system just generally is less expressive.  So while in this particular case you're observing an `Asia/Kolkata` timezone which at least has an alias to `Asia/Calcutta` you cannot assume that an IANA zone has a windows equivalent.

For instance if you observe `Canada/Mountain`, there is just no equivalent in Windows.  The same is true for `Europe/Vienna` Vienna which just does not exist in Windows.  There is a similar timezone called `Europe/Berlin`, but they are _not the same zone_.

I'm going to close this ticket because I don't believe this to be actionable here.

To be clear you can configure a timezone called `Asia/Calcutta` and it work as if it was defined as `Asia/Kolkata`.

**Comment by deifactor** [comment]
`Canada/Mountain` is defined in tzinfo as a link to `America/Edmonton`, which maps to `("Mountain Standard Time", "CA")`. Similarly, `Europe/Vienna` [does actually exist in the CLDR mapping](https://github.com/mitsuhiko/localzone/blob/main/src/windows_zones.gen.rs#L202) so I'm not sure what its relevance is.

I actually went and iterated through every timezone `tz` exposed by `chrono_tz` and, letting `canon(tz)` refer to "`tz` mapped to its canonical name using tzinfo", all but two fell into one of these categories:

- `tz` is in the CLDR database
- `canon(tz)` is in the CLDR database
- there exists some `tz2` such that `canon(tz) == canon(tz2)` and `tz` is in the CLDR database

The two exceptions are `Antarctica/Troll` (ironic name), which has no equivalent at all, and `US/Pacific-New`, which refers to a time zone created in a piece of legislation that never became law.

So aside from those two, it should be possible to map every IANA time zone onto a Windows time zone. I can send a PR if I can get my employer to okay it since I did it on the clock.
